const fs = require("fs");
const path = require("path");
const SRC = path.join(__dirname, "..", "_src");

const rebrand = (s) =>
  s
    .replace(/<!--[\s\S]*?-->/g, "")
    .replace(/Jaspreet Impex/g, "TJ Sea Logistics")
    .replace(/>JI</g, ">TJ<")
    .replace(/\+91 98767 03899/g, "+91 628490 0399")
    .replace(/98767 03899/g, "628490 0399")
    .replace(/22\+/g, "3+")
    .replace(/jaspreetimpex\.com/g, "tjsealogistics.com")
    .replace(/sunilchauhan@gmail\.com \/ 1234567890-/g, "admin@tjsealogistics.com / admin12345")
    .replace(/<span class="timeline-year">2000s</g, '<span class="timeline-year">2023<')
    .replace(/<span class="timeline-year">2010s</g, '<span class="timeline-year">2024<')
    .replace(/<span class="timeline-year">2015</g, '<span class="timeline-year">2024<')
    .replace(/<span class="timeline-year">2018</g, '<span class="timeline-year">2025<')
    .replace(/<span class="timeline-year">2020</g, '<span class="timeline-year">2025<')
    .replace(/<span class="timeline-year">2024</g, '<span class="timeline-year">2026<');

const body = (name) => fs.readFileSync(path.join(SRC, name + "-body.html"), "utf8");

const split = (html) => {
  const login = html.indexOf('<div class="login-page"');
  if (login !== -1) return { header: "", main: html, footer: "" };
  const mainStart = html.indexOf("<main");
  const footStart = html.indexOf("<footer");
  return {
    header: html.slice(0, mainStart).replace(/^[\s\S]*?<div hidden="">.*?<\/div>/, ""),
    main: html.slice(mainStart, footStart),
    footer: html.slice(footStart),
  };
};

const pages = {};
for (const n of [
  "home",
  "about-us",
  "services",
  "photos",
  "contact-us",
  "login",
  "privacy-policy",
  "terms-of-service",
]) {
  const { header, main, footer } = split(body(n));
  pages[n] = { header: rebrand(header), main: rebrand(main), footer: rebrand(footer) };
}
// single shared header/footer from home
const out =
  "// auto-generated by scripts/gen.js - do not edit\nmodule.exports = " +
  JSON.stringify(
    { header: pages.home.header, footer: pages.home.footer, mains: Object.fromEntries(Object.entries(pages).map(([k, v]) => [k, v.main])) },
    null,
    0
  ) +
  ";\n";
fs.mkdirSync(path.join(__dirname, "..", "lib"), { recursive: true });
fs.writeFileSync(path.join(__dirname, "..", "lib", "content.js"), out);
console.log("generated lib/content.js", (out.length / 1024).toFixed(1) + "KB");
